{"uuid": "27647e46-f4b5-4d0c-bbc2-eb796010cf70", "children": ["ed80d1b5-ce73-488f-a3ca-122b905fc56d"], "befores": [{"name": "browser", "status": "passed", "start": 1625834492695, "stop": 1625834511713}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=91.0.4472.124)\n\n", "trace": "  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Владимир\\PycharmProjects\\autotest_staging\\CS\\conftest.py\", line 39, in browser\n    browser.save_screenshot('Screenshots/screenshot-%s.png' % now)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1043, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1020, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1052, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1062, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1625834530630, "stop": 1625834542883}], "start": 1625834492695, "stop": 1625834542883}