{"uuid": "4add138c-f387-4818-b867-5463f2f86b6d", "children": ["75269b4d-63ae-4d13-bf48-0d45079b36c0"], "befores": [{"name": "browser", "status": "passed", "start": 1624461980432, "stop": 1624461984266}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=91.0.4472.114)\n\n", "trace": "  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Владимир\\PycharmProjects\\autotest_staging\\CS\\conftest.py\", line 39, in browser\n    browser.save_screenshot('Screenshots/screenshot-%s.png' % now)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1043, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1020, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1052, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1062, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1624462070530, "stop": 1624462070535}], "start": 1624461980432, "stop": 1624462070535}